# Site settings
title: David Marshall's blog.
email: oink@verspiglad.co.uk
description: > # this means to ignore newlines until "baseurl:"
  David Marshall spells out his amateur account of describing his life in London, and the things that he enjoys. 
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://davemarshall.netlify.com/" # the base hostname & protocol for your site
twitter_username: redpuppy
github_username:  verspiglad

# Build settings
markdown: kramdown
